name       : coin3d
version    : 4.0.0
release    : 5
source     :
    - https://github.com/coin3d/coin/releases/download/Coin-4.0.0/coin-4.0.0-src.tar.gz : e4f4bd57804b8ed0e017424ad2e45c112912a928b83f86c89963df9015251476
homepage   : https://coin3d.github.io/
license    : BSD-3-Clause
component  : multimedia.library
summary    : Coin3D core library
description: |
    Coin is an OpenGL-based, 3D graphics library that has its roots in the Open Inventor 2.1 API, which Coin still is compatible with.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(fontconfig)
    - pkgconfig(openal)
    - bzip2-devel
    - doxygen
    - libboost-devel
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %patch -p1 < $pkgfiles/0001-build_fixes.patch
    %cmake_ninja \
        -DCOIN_BUILD_DOCUMENTATION=ON \
        -DCOIN_BUILD_DOCUMENTATION_MAN=ON \
        -DHAVE_MULTIPLE_VERSION=ON \
        -DUSE_EXTERNAL_EXPAT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/{doc,info}
    cd $installdir/usr/share/man/man3
    rename "" Coin_ [a-z]*.3
