name       : coin3d
version    : 3.1.3
release    : 2
source     :
    - https://bitbucket.org/Coin3D/coin/downloads/Coin-3.1.3.tar.gz : 583478c581317862aa03a19f14c527c3888478a06284b9a46a0155fa5886d417
license    : BSD-3-Clause
component  : programming
summary    : 3D graphics toolkit
description: |
    Coin3D is a high-level, retained-mode toolkit for effective 3D graphics development. It is API compatible with Open Inventor 2.1.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(glu)
    - pkgconfig(openal)
    - bzip2-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-fix_headers.patch
    %configure \
        --enable-3ds-import \
        --enable-javascript-api \
        --enable-threadsafe \
        --disable-dl-fontconfig \
        --disable-dl-freetype \
        --disable-dl-glu \
        --disable-dl-libbzip2 \
        --disable-dl-openal \
        --disable-dl-zlib \
        --with-freetype=/usr
build      : |
    %make
install    : |
    %make_install
